### ISSUE TITLE
Use satellite.M in place of impacts.M from EXIO 3 

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/USEEIO#17]
https://github.com/USEPA/USEEIO/blob/c4eb1700cdaf1345a584a81dbf94e74f2e3f8681/import_factors_exio/Exiobase_downloads.py#L24

Right now we get this characterized matrix ..this is equivalent to our N. 

But there is also satellite.M
There are many flows for the major GHGs in satellite.M which is perhaps why we choose a characterized version, however, we are missing some important flows like.  We should probably get the unit data as well.
We can use grep on all the flows and get those starting with the major GHGs.  

If we use satellite.M we can also get SF6, HFCs (as a group) and PFCs (as a group). It's more complete than the three gases that we are getting now.

**Comment by bl-young** [comment]
Later on w/ integration with flowsa we can utilize flow mapping files for more consistency and transparency, but for now may not be worth integrating a flow mapping file

**Comment by bl-young** [comment]
Flagging that in making this update, it is not clear to me how to interpret the impacts data that we had been using previously. It appears to be in CO2e but the values in the satellite table for raw gas do not match when we apply the expected characterization factor. Ultimately I think this is further reason to use the satellite tables instead of impacts.
